spring:
  application:
    name: billcalc
server:
  port: 8292
billcalc:
  coins:
    availableCoins: #out of order on purpose
      0.10: 100
      0.25: 100
      0.01: 100
      0.05: 100
  bills:
    allowedBills:
      - 1
      - 2
      - 5
      - 10
      - 20
      - 50
      - 100
